[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tcrates/sovereign-kernel/linker-x86_64.ld",
    "-C", "relocation-model=static",
    "-C", "target-feature=-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2",
]

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tcrates/sovereign-kernel/linker-aarch64.ld",
    "-C", "relocation-model=static",
]
