[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tcrates/sovereign-kernel/linker-x86_64.ld",
    "-C", "relocation-model=static",
]

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tcrates/sovereign-kernel/linker-aarch64.ld",
    "-C", "relocation-model=static",
]
